In [22]:
import pandas as pd
import random
import numpy as np

In [10]:
# other - Others (1895 - 1923)
dfo = pd.read_csv('catalog_v0.xlsx - other.csv')
dfo['Classe'] = 0

sample_list = [0.028878193261754906, 0.40067567567567564, 0.059625055724921355, 0.00557351131212664, 0.0443319050197565, 0.013513513513513514]
medidas_other = []

for _ in range(len(dfo)):
    random_list = [random.uniform(min(sample_list), max(sample_list)) for _ in sample_list]
    medidas_other.append(random_list)

dfo["Medidas"] = medidas_other
dfo.head()

,Title,Author,Year,Index,Classe,Medidas
0,In the Land Of Cave And Cliff Dwellers,Frederick Schwatka,1895,1,0,"[0.057113648021126125, 0.15516440717584687, 0...."
1,Jude the Obscure,Thomas Hardy,1895,2,0,"[0.267783547319531, 0.11901050984663683, 0.115..."
2,The Golden Age,Kenneth Grahame,1895,3,0,"[0.31954978096660336, 0.29762443391406646, 0.2..."
3,The Lost Stradivarius,John Meade Falkner,1895,4,0,"[0.12740765194101653, 0.17336540373593137, 0.1..."
4,The British Barbarians,Grant Allen,1895,5,0,"[0.045649424290438195, 0.31587885154109724, 0...."

In [14]:
# success- Publishers Weekly’s Bestselling Novels
dfs = pd.read_csv('catalog_v0.xlsx - success.csv')
dfs['Classe'] = 1

medidas_success = []

for _ in range(len(dfs)):
    random_list = [random.uniform(min(sample_list), max(sample_list)) for _ in sample_list]
    medidas_success.append(random_list)

dfs['Medidas'] = medidas_success
dfs.head()

,Title,Author,Year,Index,Classe,Medidas
0,Beside the Bonnie Brier Bush,Ian Maclaren,1895,1,1,"[0.24997520937720716, 0.38591055429235915, 0.0..."
1,Trilby,George Du Maurier,1895,2,1,"[0.15427645550367305, 0.19876465311364497, 0.3..."
2,The Adventures of Captain Horn,Frank Richard Stockton,1895,3,1,"[0.3315759428180149, 0.24249724054982405, 0.38..."
3,The Manxman,Hall Caine,1895,4,1,"[0.34996090701129173, 0.18309809697931073, 0.0..."
4,The Princess Aline,Richard Harding Davis,1895,5,1,"[0.3312776614346902, 0.3220676293809049, 0.042..."

In [17]:
concat = pd.concat([dfs, dfo], axis=0)
concat = concat.sample(frac=1).reset_index(drop=True)
display(concat)

,Title,Author,Year,Index,Classe,Medidas
0,The Sheep-Stealers,Violet Jacob,1902,41,0,"[0.15615092553657522, 0.21508646245193372, 0.2..."
1,A Singular Life,Elizabeth Stuart Phelps Ward,1896,13,1,"[0.2461545458480473, 0.36409627139333073, 0.37..."
2,Windy McPherson’s Son,Sherwood Anderson,1916,85,0,"[0.22947992761618574, 0.29982701987083266, 0.1..."
3,The Lone Star Ranger,Zane Grey,1915,88,1,"[0.2520184911027355, 0.2707687663805753, 0.214..."
4,A Diary from Dixie,Mary Boykin Miller Chesnut,1905,54,0,"[0.10536617977430934, 0.11434815306725471, 0.3..."
...,...,...,...,...,...,...
214,The Love Story of Aliette Brunton,Gilbert Frankau,1922,107,0,"[0.29907292085937803, 0.1804022492326282, 0.23..."
215,In His Steps,Charles M. Sheldon,1896,14,0,"[0.1693423303110842, 0.32957652503453033, 0.02..."
216,The Pride of Jennico,Egerton Castle,1898,25,1,"[0.2646464379089874, 0.2638169176463951, 0.356..."
217,The Fighting Chance,Robert W. Chambers,1906,61,1,"[0.32143216697086, 0.2865202398453358, 0.35618..."
218,The Virginian,Owen Wister,1902,43,1,"[0.31866644801558225, 0.14006419102981127, 0.0..."

In [18]:
for i in range(len(concat)):
    name = ''.join(concat["Title"][i].split())
    index = concat["Index"][i]
    namesearch = str(index) + '_' + str(name)
    print(namesearch)

41_TheSheep-Stealers
13_ASingularLife
85_WindyMcPherson’sSon
88_TheLoneStarRanger
54_ADiaryfromDixie
33_TheWalletofKaiLung
87_TheHarbor
12_AChildoftheJago
71_TheReturn
16_TheWhirlpool
35_TheBrassBottle
70_Katrine
102_TheBeautifulandDamned
63_TheJungle
108_LadyIntoFox
39_ThePurpleCloud
1_BesidetheBonnieBrierBush
44_TheFlightofPonyBaker
45_TheRiddleOfTheSands
55_WhereAngelsFeartoTread
85_DianeoftheGreenVan
70_PresterJohn
58_TheGardenofAllah
37_TheRedemptionofDavidCorson
26_Shrewsbury
42_ADaughteroftheSnows
59_RomanceIsland
98_TheTinSoldier
74_TheQuestoftheSilverFleece
11_TheWellattheWorld'sEnd
60_LoveAmongtheChickens
77_ThePromisedLand
79_TheHarvester
16_TheRedBadgeofCourage
50_TheIslandPharisees
55_IntheBishop'sCarriage
15_HistoryoftheWarfareofSciencewithTheologyinChristendom
49_TheNapoleonofNottingHill
48_ThirtyYearsinAustralia
108_SimonCalledPeter
72_ZuleikaDobson
102_MainStreet
26_TheGoldenCanyon
89_Mr.BritlingSeesItThrough
9_Madelon
34_SisterCarrie
8_Degeneration
59_TheHouseofMirth
40_ThePuppetCrown
81_TheKingofAlsander
7_ThePrisonerofZenda
97_TheArrowofGold
29_RichardCarvel
47_TheTwoVanrevels
52_TheCommonLot
80_Trent'sLastCase
45_TheMississippiBubble
86_TheDevil'sGarden
76_TheEyeofOsiris
99_KindredoftheDust
3_TheAdventuresofCaptainHorn
109_MariaChapdelaine
109_WhoseBody?
43_TheFourFeathers
7_RoseofDutcher'sCoolly
62_Pip
13_TomSawyer,Detective
56_MyFriendProspero
38_AliceofOldVincennes
31_TheWonderfulWizardofOz
35_UnleavenedBread
93_TheHeartofRachael
83_IPose
38_MyBrilliantCareer
110_TheSeaHawk
44_Mrs.WiggsoftheCabbagePatch
60_ThePrincessPasses
42_Graustark
30_ABookoftheWest
6_TheSorrowsofSatan
57_TheEducationofHenryAdams
67_ThePromiseOfAmericanLife
98_TheMysteriousAffairatStyles
47_TheJewelofSevenStars
87_Metamorphosis
75_DawnO'Hara
79_MatesatBillabong
1_IntheLandOfCaveAndCliffDwellers
22_HughWynne
94_Tarr
46_LongWill
67_SatanSanderson
78_Mrs.Ames
106_TheKingdomRoundtheCorner
10_TomGrogan
73_TheHampdenshireWonder
33_ToHaveandtoHold
10_TheCountryofthePointedFirs
36_EbenHolden
76_TheProdigalJudge
94_TheTreeofHeaven
56_TheScarletPimpernel
103_SheandAllan
86_Mendel
52_TheLittleShepherdofKingdomCome
23_TheUncalled
2_Trilby
50_ThePit
100_TheRiver'sEnd
93_PatriciaBrent,Spinster
78_Queed
62_TheHouseofaThousandCandles
17_TheBethBook
103_TheBrimmingCup
14_TheDamnationofTheronWare
2_JudetheObscure
89_SevenMilestoArden
64_TheAwakeningofHelenaRichie
73_TheRosary
74_MollyMake-Believe
5_ThePrincessAline
68_TheDoctor
69_TheInnerShrine
101_MysteryRanch
36_ErewhonRevisited
37_TheHousewiththeGreenShutters
34_RedPottage
4_TheLostStradivarius
64_TheHillofDreams
6_TheMaster
24_TheSecondThoughtsofanIdleFellow
19_TheChoirInvisible
15_AHouse-BoatontheStyx
51_TheOneWoman
5_TheBritishBarbarians
82_Fran
80_TheMeltingofMolly
104_TheBlackMoth
68_ElusiveIsabel
57_TheSilentPlaces
4_TheManxman
39_TheHelmetofNavarre
53_TheDeliverance
100_ThreeSoldiers
18_QuoVadis
106_Ulysses
27_SomeExperiencesofanIrishR.M.
90_TheRealAdventure
77_TheWinningofBarbaraWorth
22_AManfromtheNorth
21_TheHonorablePeterStirling
96_TheYoungVisiters
24_HelbeckofBannisdale
58_TheFifthQueen
11_ALadyofQuality
28_WoodandGarden
72_Septimus
65_TheSpoilers
20_OntheFaceoftheWaters
95_TheValleyofSquintingWindows
19_TheBeetle
27_DavidHarum
23_Penelope'sProgress
101_ThePortygee
46_TheHoundoftheBaskervilles
97_Jurgen
84_SongoftheLark
91_BarsofIron
20_AddedUpon
53_GreenMansions
29_TheTheoryoftheLeisureClass
75_TheBroadHighway
84_TheSalamander
95_ThePawnsCount
25_EvelynInnes
88_Backwater
18_TheSpoilsofPoynton
71_TheManinLowerTen
90_TheBeastsofTarzan
8_Yekl:ATaleoftheNewYorkGhetto
105_TheSisters-in-Law
83_Pollyanna
32_Mr.DooleyinPeaceandWar
51_CabbagesandKings
91_RegimentofWomen
31_Aylwin
9_MyLadyNobody
65_FatherandSon
105_CromeYellow
63_TheMysteryof“TheYellowRoom”
3_TheGoldenAge
54_TheMasquerader
41_TheLifeandDeathofRichardYea-and-Nay
107_IfWinterComes
66_Jimbo
92_NanofMusicMountain
32_TheInfidel
28_WhenKnighthoodWasinFlower
40_UpFromSlavery
49_SirRichardCalmady
48_TheBlueFlower
96_Sonia
81_Tante
92_Meccania
12_TheSeatsoftheMighty
21_ADigitoftheMoon
69_MultitudeandSolitude
104_TheSheik
61_TheFortunesofPhilippa
66_TheBrassBowl
82_BirdofParadise
17_SentimentalTommy
99_Alf'sButton
30_RedRock
107_TheLoveStoryofAlietteBrunton
14_InHisSteps
25_ThePrideofJennico
61_TheFightingChance
43_TheVirginian

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

# dados
X = np.array(concat['Medidas'])
y = list(concat['Classe']) # classes de sucesso
print("classes de sucesso:", y)

# Separar em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Treinamento do modelo (usando KNN neste exemplo)
knn = KNeighborsClassifier(n_neighbors=5)  # K=5 para o exemplo, ajuste conforme necessário
knn.fit(X_train, y_train)

# Previsão das classes para o conjunto de teste
y_pred = knn.predict(X_test)

classes de sucesso: [0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1]

ValueError: setting an array element with a sequence.